### ISSUE TITLE
WooCommerce notifications

### ISSUE THREAD

**Issue by stefan-cotitosu** [ancapantilie/nystia#2]
Try to style WooCommerce notification like these. Color should be fixed depending on the notification type.

Single Product Page
![single-product-notification](https://user-images.githubusercontent.com/26867648/36226567-d8d8282c-11d6-11e8-9bc2-71fa478189f3.png)

Cart Updated
![cart-updated-notification](https://user-images.githubusercontent.com/26867648/36226659-20880fa2-11d7-11e8-8ab9-fd80e9f6aba9.png)

Product removed from cart
![product-removed-from-cart](https://user-images.githubusercontent.com/26867648/36226773-78d9d46a-11d7-11e8-88ef-eabb4ab3d68c.png)

Empty cart
![empty-cart](https://user-images.githubusercontent.com/26867648/36226817-9bc4e0be-11d7-11e8-9fdb-910a89b74c94.png)

Checkout notification
![checkout-notification](https://user-images.githubusercontent.com/26867648/36226718-52a28698-11d7-11e8-99ab-31a24d16e8f8.png)

These are some examples, you should try more WooCommerce actions including the widgets, like add to cart, change the cart, empty it, proceed to checkout and so on.

**Comment by ancapantilie** [comment]
@stefan-cotitosu I played a bit with the actions (I added items in the cart, I removed some of them and I also tried to update the cart) and the notifications I get look the same as those in the screenshots you attached.Would you mind explaining again what exactly do I have to do?
