### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by stefan-cotitosu** [ancapantilie/nystia#3]
Try to style cart table like this. Don't worry about the description column.
<img width="1084" alt="cart" src="https://user-images.githubusercontent.com/26867648/36227133-bc529eb0-11d8-11e8-869c-94cbde11bb84.png">

Also take care of Cart Totals sidebar, especially font properties. remove the box shadow from the box and the button.
![cart-totals](https://user-images.githubusercontent.com/26867648/36227213-01663412-11d9-11e8-96a5-b7e20f844173.png)

**Comment by stefan-cotitosu** [comment]
When Cart is empty, the button has a shadow on hover. Please remove the shadow.
<img width="1296" alt="cart1" src="https://user-images.githubusercontent.com/26867648/36640870-9e4cf6b8-1a2f-11e8-9a6a-d6809d61801e.png">

Check the page title color again.
<img width="1541" alt="cart2" src="https://user-images.githubusercontent.com/26867648/36640994-783fabc6-1a31-11e8-9fde-8fae55ba9323.png">

Check **font-size** and **line-height** on product column. font-size should be 22px instead of 20px, check line-height too.
<img width="798" alt="cart3" src="https://user-images.githubusercontent.com/26867648/36641021-f88eef3a-1a31-11e8-8f31-82aa52e51591.png">

Price column has font-size: 22px instead of 21px. Check all columns, **font-size** and **line-height** is different than the design on all of them.

**Comment by ancapantilie** [comment]
@stefan-cotitosu I checked and product,price,quantity and total have **font-size:22px;** in the design. I modified the font of product column from 20px to 22px and line-height from 21px to 22px. That was the closest I could get to the design value.
