### ISSUE TITLE
Single Post Page

### ISSUE THREAD

**Issue by stefan-cotitosu** [ancapantilie/nystia#7]
Check the social icons, remove the **box-shadow** effect on hover and follow the design. It changes the opacity on hover, I think you can do that too :wink:
http://gsdk.creative-tim.com/blog-post

Check the labels for categories and tags.
Here is how they look now.
![labels1](https://user-images.githubusercontent.com/26867648/36676211-b1ddb5de-1b13-11e8-8aeb-49be833464ef.png)

Here is how it should be.
![labels2](https://user-images.githubusercontent.com/26867648/36676216-b56cbbf0-1b13-11e8-8b1b-936d99ddaf2e.png)

You can use filled labels for Categories and transparent ones for Tags.

When you think that this page is finished, please check the Typography controls on Single Post Page. Make sure that they work in Customizer and on the Site too.
![single_post_1](https://user-images.githubusercontent.com/26867648/36676370-31ebfd30-1b14-11e8-8fa1-d202d96c95bb.png)

**Comment by ancapantilie** [comment]
@stefan-cotitosu Wouldn't it be more interesting if I'd try to change how the social buttons appear?Something different than the ones Hestia has. There's plenty of choices
![screenshot_1](https://user-images.githubusercontent.com/28201243/36848741-d05c2992-1d6a-11e8-9213-354e12769f36.png)
